# Application Name
spring.application.name=totem

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Swagger
springdoc.swagger-ui.path=/docs

# Health Check Endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
